Feature/download as
ONLYOFFICE/onlyoffice-alfresco pull request #105
Opened 2021-09-08 19:52 UTC by olejiksin

add feature download as... file or selected multiple files

2021-09-14 08:13 UTC, aleksandrfedorov97 approved these changes

2021-09-16 12:27 UTC, Eloncase approved these changes

2021-09-27 07:57 UTC, LinneyS requested changes

2021-09-27 07:57 UTC, LinneyS commented on share/src/main/resources/META-INF/components/documentlibrary/onlyoffice-doclib-multi-download-as.js
> +    var textInputType = ["doc", "docm", "docx", "dot", "dotm", "dotx", "epub", "fb2", "fodt", "html", "mht", "odt", "ott", "pdf", "rtf", "txt", "xps", "xml"];
try to remove the duplicate

2021-09-27 21:02 UTC, aleksandrfedorov97 approved these changes

2021-09-27 21:15 UTC, aleksandrfedorov97 approved these changes

2021-09-28 07:56 UTC, aleksandrfedorov97 approved these changes

2021-09-28 10:07 UTC, merged