Feature/templates
ONLYOFFICE/onlyoffice-alfresco pull request #95
Opened 2021-08-04 14:43 UTC by olejiksin

creating new file from document editor by document template

2021-08-05 07:00 UTC, Eloncase approved these changes

2021-08-05 07:57 UTC, aleksandrfedorov97 requested changes

2021-08-05 07:57 UTC, aleksandrfedorov97 commented on repo/src/main/java/com/parashift/onlyoffice/Prepare.java
> +                        URL url = new URL(util.getContentUrl(parentNodeRef));
get inputStream using contentService.getReader()

2021-08-05 07:57 UTC, aleksandrfedorov97 commented on share/src/main/resources/alfresco/site-webscripts/com/parashift/onlyoffice-edit.get.html.ftl
> +
is it possible to get an templatings object on the server side?

2021-08-06 10:27 UTC, aleksandrfedorov97 approved these changes

2021-08-06 10:51 UTC, LinneyS requested changes

2021-08-06 10:51 UTC, LinneyS commented on share/src/main/resources/alfresco/site-webscripts/com/parashift/onlyoffice-edit.get.js
> +if (url.args.parentNodeRef) query+= "&parentNodeRef=" + url.args.parentNodeRef;
encodeURIComponent

2021-08-06 10:51 UTC, LinneyS commented on share/src/main/resources/alfresco/site-webscripts/com/parashift/onlyoffice-edit.get.js
>  var query = "?nodeRef=" + url.args.nodeRef;
encodeURIComponent

2021-08-06 10:51 UTC, LinneyS commented on repo/src/main/java/com/parashift/onlyoffice/Util.java
> +                String url = getCreateNewUrl(nodeRef, mimeType) + "&parentNodeRef=" + assoc.getChildRef();
encode

2021-08-29 15:25 UTC, merged