Feature/favorites
ONLYOFFICE/onlyoffice-alfresco pull request #96
Opened 2021-08-04 14:45 UTC by olejiksin

changing favorite flag of the file from document editor

2021-08-05 07:13 UTC, Eloncase approved these changes

2021-08-06 10:50 UTC, aleksandrfedorov97 requested changes
![image](https://user-images.githubusercontent.com/62958171/128499552-9a74f2ec-0181-4ecc-a09c-976368b31b04.png)
when i try set favorite from editor

2021-08-06 11:05 UTC, LinneyS requested changes

2021-08-06 11:05 UTC, LinneyS commented on share/src/main/resources/alfresco/site-webscripts/com/parashift/onlyoffice-edit.get.js
> +model.favo = pObj.favo;
use full name instead of abbreviation

2021-08-29 15:29 UTC, merged